server:
    servlet.context-path: /api
    port: 8090
    ssl:
        key-store-type: PKCS12
        key-store: ${HOME}/cert/tracer.p12
        key-store-password: change_me_key
        key-alias: tracer-service
        enabled: true

keycloak:
    auth-server-url: "http://localhost:8080/auth"
    realm: CHAIMELEON
    resource: tracer-service
    public-client: true
    
spring:
    h2.console.enabled: true
    datasource:
        url: jdbc:h2:file:${HOME}/tracer.db;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa.database-platform: org.hibernate.dialect.H2Dialect
    
tracer:
    disableSSLVerification: false
    admin:
        name: admin
        password: change_me
    hashAlgorithm: SHA3-256
    yearMin: 2021
    yearMax: 2024
    entity: UPV-I3M-GRyCAP
    version: ^project.version^

blockchain:
    # http://localhost:9984/api/v1
    tmpHashDownFolder: /tmp/tracer/
    besu:
        enabled: false
        url: https://localhost:1443/ 
    bigchaindb:
        enabled: true
        url: https://asaserver.i3m.upv.es:9984/ 
        transactionModePost: sync
        defaultAmountTransaction: 1
        keypairPrivate: /tmp/ed25519
        keypairPublic: /tmp/ed25519.pub
