spring:
    datasource:
        url: jdbc:h2:file:${HOME}/tracer.db;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        ddl-auto: none
        
        
tracer:
    # in KB
    request-parse-limit: 128
    cache:
        threads: 20
        # in seconds
        retry-delay: 300