base-dir: ${HOME}/tmp/tracer
cache-db-name: tracer.db

server:
    port: 8090
    ssl:
        key-store-type: PKCS12
        key-store: ${HOME}/cert/tracer.p12
        key-store-password: change_me_key
        key-alias: tracer-service
        enabled: true
      
logging.level.org.springframework.web:
    filter.CommonsRequestLoggingFilter: DEBUG
    reactive.function.client.ExchangeFunctions: DEBUG

keycloak:
    auth-server-url: "https://asaserver.i3m.upv.es:20000/auth"
    realm: CHAIMELEON
    resource: tracer-service
    public-client: true
    bearer-only: true
    
spring:
    h2.console.enabled: true
    datasource:
        url: jdbc:h2:file:${base-dir}/${cache-db-name};DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect        
        hibernate:
            ddl-auto: update
        properties:
            open-in-view: false
            hibernate:
                enable_lazy_load_no_trans: true
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        client-id: tracer-service
#                        client-secret: 
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8090/api/v1
                        scope: profile
#                        realm: CHAIMELEON
#                        public-client: true
#                        provider: keycloak
                provider:
                    keycloak:
                        authorization-uri: https://localhost:20000/auth/realms/CHAIMELEON/protocol/openid-connect/auth
#                        jwk-set-uri:  https://localhost:20000/auth/realms/CHAIMELEON/protocol/openid-connect/certs
#                        issuer-uri: https://localhost:20000/auth/realms/CHAIMELEON
                        token-uri: https://localhost:20000/auth/realms/CHAIMELEON/protocol/openid-connect/token
                        user-name-attribute: preferred_username
                        
tracer:
    # in KB
    request-parse-limit: 128
    cache:
        threads: 20
        # in seconds
        retry-delay: 60
    disableSSLVerification: false
    admin:
        name: admin
        password: change_me
    hashAlgorithm: SHA3-256
    time:
        useLocal: false
        ntpTimeout: 5000
        timeServers: 
            - pool.ntp.org
            - time.nist.gov
            - time-a-g.nist.gov
            - time-b-g.nist.gov
            - time-c-g.nist.gov
            - time-d-g.nist.gov
            - time-e-g.nist.gov
            - time-a-wwv.nist.gov
            - time-b-wwv.nist.gov
            - time-c-wwv.nist.gov
            - time-d-wwv.nist.gov
            - time-e-wwv.nist.gov
            - time-a-b.nist.gov
            - time-b-b.nist.gov
            - utcnist.colorado.edu
            - utcnist2.colorado.edu
        retries: 3
    info:
        yearMin: 2021
        yearMax: 2024
        entity: "UPV-I3M-GRyCAP"
        version: ^project.version^
        name: "Tracer Web Service"
        api:
            v1:
                traces: /api/v1/traces

blockchain:
    # http://localhost:9984/api/v1
    tmpHashDownFolder: ${base-dir}/tmp-hash
    besu:
        private:
            enabled: true
            name: "Besu Private"
            url: http://127.0.0.1:35395/rpc
            contracts:
                - name: ChaimeleonTracer_V1
                  enable: 
                    add: true
                    read:  true              
                  deployed: ${base-dir}/besu/contract/ChaimeleonTracer_V1.json
            wallet:
                password: eth-test
                path: ${base-dir}/besu/wallet
    bigchaindb:
        private:
            enabled: false
            name: "BigchainDB Private"
            url: http://asaserver.i3m.upv.es:9984/api/v1
            transactionModePost: commit
            defaultAmountTransaction: 1
            keypairPrivate: ${base-dir}/bigchaindb/keys/ed25519
            keypairPublic: ${base-dir}/bigchaindb/keys/ed25519.pub
