server.servlet.context-path: /api
server.port: 8090

keycloak:
    auth-server-url: "http://localhost:8080/auth"
    realm: CHAIMELEON
    resource: tracer-service
    public-client: true
spring:
    h2.console.enabled: true
    datasource:
        url: jdbc:h2:file:~/tracer.db;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa.database-platform: org.hibernate.dialect.H2Dialect
    
tracer:
    admin:
        name: admin
        password: change_me
    hashAlgorithm: SHA3-256
    yearMin: 2021
    yearMax: 2024
    entity: UPV-I3M-GRyCAP
    version: ^project.version^
    keypair:
        private: /tmp/ed25519
        public: /tmp/ed25519.pub

blockchaindb:
    baseUrl: http://localhost:9984/api/v1
    transactionModePost: sync
    tmpHashDownFolder: /tmp/tracer/
    defaultAmountTransaction: 1
